outputs:
  home: ["HTML", "RSS", "JSON"]

# baseURL: "https://graham-ambrose/hugo-website/" 
# baseURL: "https://soham-gundewar/hugo-website-gambrose/" 
# baseURL: "http://graham-ambrose.online/"
baseURL : "https://ambro034.github.io/Portfolio-Website/" 
title: Graham Ambrose
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research Bio
          url: research/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Books
          url: books/
          weight: 4
        - name: Tags
          url: tags/
          weight: 5


params:
    description: "This website hosts Graham Ambrose's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Graham Ambrose
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data","research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Graham Ambrose
          subtitle: " I am a public administration scholar focusing on the fields of collaborative governance and policy process with an expertise and interest in local food and environmental governance and policy design."
          description: "My research utilizes a policy process lens to explore representation in collaborative fora and the evolution of policy design, examining how diverse participation and institutional dynamics shape governance outcomes."
          imageUrl: "profile-picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research Bio
              url: research/
            - name: Courses
              url: courses/
            - name: Papers
              url: papers/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
  

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:gambros@ncsu.edu
        - name: YouTube
          url: https://www.youtube.com/@ArtOfSciencePod
        - name: Office Hours
          url: officehours/
        - name: Zoom
          url: officehours/
          title: "Request appointment to receive Zoom link"
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=MZ5VmHMAAAAJ&hl=en&oi=sra
        - name: GitHub
          url:  https://github.com/ambro034

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Graham Ambrose"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
